
sequenceDiagram
    participant browser
    participant server

    browser->>server: HTTP GET /spa
    server->>browser: main.html
    browser->>server: HTTP GET /spa
    server->>browser: main.css
    browser->>server: HTTP GET /spa
    server->>browser: main.js
    browser->>server: HTTP GET /spa
    server->>browser: data.json